apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: piranid
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: docker.io/library/piranid-database:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          env:
            - name: DB_SERVICE_PORT
              value: "8085"
            - name: API_VERSION
              value: "v1"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: piranid
spec:
  selector:
    app: database
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30085
