apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging
  namespace: piranid
  labels:
    app: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
    spec:
      containers:
        - name: logging
          image: docker.io/library/piranid-logging:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: LOGGING_SERVICE_PORT
              value: "8083"
            - name: API_VERSION
              value: "v1"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: logging
  namespace: piranid
spec:
  selector:
    app: logging
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30083
