// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: notifications/v1/notifications.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_FAILURE Status = 0
	Status_SUCCESS Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "FAILURE",
		1: "SUCCESS",
	}
	Status_value = map[string]int32{
		"FAILURE": 0,
		"SUCCESS": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_notifications_v1_notifications_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_notifications_v1_notifications_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{0}
}

type NotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Importance    int32                  `protobuf:"varint,5,opt,name=importance,proto3" json:"importance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationRequest) Reset() {
	*x = NotificationRequest{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequest) ProtoMessage() {}

func (x *NotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequest.ProtoReflect.Descriptor instead.
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *NotificationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *NotificationRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *NotificationRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *NotificationRequest) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

type NotificationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         Status                 `protobuf:"varint,1,opt,name=success,proto3,enum=notifications.v1.Status" json:"success,omitempty"`
	ResponseMessage *string                `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3,oneof" json:"response_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationResponse) GetSuccess() Status {
	if x != nil {
		return x.Success
	}
	return Status_FAILURE
}

func (x *NotificationResponse) GetResponseMessage() string {
	if x != nil && x.ResponseMessage != nil {
		return *x.ResponseMessage
	}
	return ""
}

type UserNotificationUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	ContactInfo   string                 `protobuf:"bytes,3,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"` // check for @, if not there, it's phone
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserNotificationUpdate) Reset() {
	*x = UserNotificationUpdate{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserNotificationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNotificationUpdate) ProtoMessage() {}

func (x *UserNotificationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNotificationUpdate.ProtoReflect.Descriptor instead.
func (*UserNotificationUpdate) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *UserNotificationUpdate) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *UserNotificationUpdate) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserNotificationUpdate) GetContactInfo() string {
	if x != nil {
		return x.ContactInfo
	}
	return ""
}

type UserNotificationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         Status                 `protobuf:"varint,1,opt,name=success,proto3,enum=notifications.v1.Status" json:"success,omitempty"`
	ResponseMessage *string                `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3,oneof" json:"response_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserNotificationResponse) Reset() {
	*x = UserNotificationResponse{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNotificationResponse) ProtoMessage() {}

func (x *UserNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNotificationResponse.ProtoReflect.Descriptor instead.
func (*UserNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *UserNotificationResponse) GetSuccess() Status {
	if x != nil {
		return x.Success
	}
	return Status_FAILURE
}

func (x *UserNotificationResponse) GetResponseMessage() string {
	if x != nil && x.ResponseMessage != nil {
		return *x.ResponseMessage
	}
	return ""
}

type TFARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	ContactInfo   string                 `protobuf:"bytes,4,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	Timeout       *int32                 `protobuf:"varint,5,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TFARequest) Reset() {
	*x = TFARequest{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TFARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFARequest) ProtoMessage() {}

func (x *TFARequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFARequest.ProtoReflect.Descriptor instead.
func (*TFARequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *TFARequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *TFARequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TFARequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *TFARequest) GetContactInfo() string {
	if x != nil {
		return x.ContactInfo
	}
	return ""
}

func (x *TFARequest) GetTimeout() int32 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

type TFAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Success       Status                 `protobuf:"varint,3,opt,name=success,proto3,enum=notifications.v1.Status" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TFAResponse) Reset() {
	*x = TFAResponse{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TFAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFAResponse) ProtoMessage() {}

func (x *TFAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFAResponse.ProtoReflect.Descriptor instead.
func (*TFAResponse) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{5}
}

func (x *TFAResponse) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *TFAResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TFAResponse) GetSuccess() Status {
	if x != nil {
		return x.Success
	}
	return Status_FAILURE
}

var File_notifications_v1_notifications_proto protoreflect.FileDescriptor

const file_notifications_v1_notifications_proto_rawDesc = "" +
	"\n" +
	"$notifications/v1/notifications.proto\x12\x10notifications.v1\"\x86\x02\n" +
	"\x13NotificationRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12C\n" +
	"\x04data\x18\x04 \x03(\v2/.notifications.v1.NotificationRequest.DataEntryR\x04data\x12\x1e\n" +
	"\n" +
	"importance\x18\x05 \x01(\x05R\n" +
	"importance\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x01\n" +
	"\x14NotificationResponse\x122\n" +
	"\asuccess\x18\x01 \x01(\x0e2\x18.notifications.v1.StatusR\asuccess\x12.\n" +
	"\x10response_message\x18\x02 \x01(\tH\x00R\x0fresponseMessage\x88\x01\x01B\x13\n" +
	"\x11_response_message\"v\n" +
	"\x16UserNotificationUpdate\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fcontact_info\x18\x03 \x01(\tR\vcontactInfo\"\x93\x01\n" +
	"\x18UserNotificationResponse\x122\n" +
	"\asuccess\x18\x01 \x01(\x0e2\x18.notifications.v1.StatusR\asuccess\x12.\n" +
	"\x10response_message\x18\x02 \x01(\tH\x00R\x0fresponseMessage\x88\x01\x01B\x13\n" +
	"\x11_response_message\"\xad\x01\n" +
	"\n" +
	"TFARequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12!\n" +
	"\fcontact_info\x18\x04 \x01(\tR\vcontactInfo\x12\x1d\n" +
	"\atimeout\x18\x05 \x01(\x05H\x00R\atimeout\x88\x01\x01B\n" +
	"\n" +
	"\b_timeout\"|\n" +
	"\vTFAResponse\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x122\n" +
	"\asuccess\x18\x03 \x01(\x0e2\x18.notifications.v1.StatusR\asuccess*\"\n" +
	"\x06Status\x12\v\n" +
	"\aFAILURE\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x012\x8f\x03\n" +
	"\bNotifier\x12d\n" +
	"\x13RequestNotification\x12%.notifications.v1.NotificationRequest\x1a&.notifications.v1.NotificationResponse\x12[\n" +
	"\n" +
	"DeleteUser\x12%.notifications.v1.NotificationRequest\x1a&.notifications.v1.NotificationResponse\x12u\n" +
	"\x1dRequestUserNotificationUpdate\x12(.notifications.v1.UserNotificationUpdate\x1a*.notifications.v1.UserNotificationResponse\x12I\n" +
	"\n" +
	"RequestTFA\x12\x1c.notifications.v1.TFARequest\x1a\x1d.notifications.v1.TFAResponseB;Z9github.com/ayden-boyko/Piranid/pkg/proto/notifications/v1b\x06proto3"

var (
	file_notifications_v1_notifications_proto_rawDescOnce sync.Once
	file_notifications_v1_notifications_proto_rawDescData []byte
)

func file_notifications_v1_notifications_proto_rawDescGZIP() []byte {
	file_notifications_v1_notifications_proto_rawDescOnce.Do(func() {
		file_notifications_v1_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifications_v1_notifications_proto_rawDesc), len(file_notifications_v1_notifications_proto_rawDesc)))
	})
	return file_notifications_v1_notifications_proto_rawDescData
}

var file_notifications_v1_notifications_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notifications_v1_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_notifications_v1_notifications_proto_goTypes = []any{
	(Status)(0),                      // 0: notifications.v1.Status
	(*NotificationRequest)(nil),      // 1: notifications.v1.NotificationRequest
	(*NotificationResponse)(nil),     // 2: notifications.v1.NotificationResponse
	(*UserNotificationUpdate)(nil),   // 3: notifications.v1.UserNotificationUpdate
	(*UserNotificationResponse)(nil), // 4: notifications.v1.UserNotificationResponse
	(*TFARequest)(nil),               // 5: notifications.v1.TFARequest
	(*TFAResponse)(nil),              // 6: notifications.v1.TFAResponse
	nil,                              // 7: notifications.v1.NotificationRequest.DataEntry
}
var file_notifications_v1_notifications_proto_depIdxs = []int32{
	7, // 0: notifications.v1.NotificationRequest.data:type_name -> notifications.v1.NotificationRequest.DataEntry
	0, // 1: notifications.v1.NotificationResponse.success:type_name -> notifications.v1.Status
	0, // 2: notifications.v1.UserNotificationResponse.success:type_name -> notifications.v1.Status
	0, // 3: notifications.v1.TFAResponse.success:type_name -> notifications.v1.Status
	1, // 4: notifications.v1.Notifier.RequestNotification:input_type -> notifications.v1.NotificationRequest
	1, // 5: notifications.v1.Notifier.DeleteUser:input_type -> notifications.v1.NotificationRequest
	3, // 6: notifications.v1.Notifier.RequestUserNotificationUpdate:input_type -> notifications.v1.UserNotificationUpdate
	5, // 7: notifications.v1.Notifier.RequestTFA:input_type -> notifications.v1.TFARequest
	2, // 8: notifications.v1.Notifier.RequestNotification:output_type -> notifications.v1.NotificationResponse
	2, // 9: notifications.v1.Notifier.DeleteUser:output_type -> notifications.v1.NotificationResponse
	4, // 10: notifications.v1.Notifier.RequestUserNotificationUpdate:output_type -> notifications.v1.UserNotificationResponse
	6, // 11: notifications.v1.Notifier.RequestTFA:output_type -> notifications.v1.TFAResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_notifications_v1_notifications_proto_init() }
func file_notifications_v1_notifications_proto_init() {
	if File_notifications_v1_notifications_proto != nil {
		return
	}
	file_notifications_v1_notifications_proto_msgTypes[1].OneofWrappers = []any{}
	file_notifications_v1_notifications_proto_msgTypes[3].OneofWrappers = []any{}
	file_notifications_v1_notifications_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifications_v1_notifications_proto_rawDesc), len(file_notifications_v1_notifications_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notifications_v1_notifications_proto_goTypes,
		DependencyIndexes: file_notifications_v1_notifications_proto_depIdxs,
		EnumInfos:         file_notifications_v1_notifications_proto_enumTypes,
		MessageInfos:      file_notifications_v1_notifications_proto_msgTypes,
	}.Build()
	File_notifications_v1_notifications_proto = out.File
	file_notifications_v1_notifications_proto_goTypes = nil
	file_notifications_v1_notifications_proto_depIdxs = nil
}
