// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: notifications/v1/notifications.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Notifier_RequestNotification_FullMethodName           = "/notifications.v1.Notifier/RequestNotification"
	Notifier_DeleteUser_FullMethodName                    = "/notifications.v1.Notifier/DeleteUser"
	Notifier_RequestUserNotificationUpdate_FullMethodName = "/notifications.v1.Notifier/RequestUserNotificationUpdate"
	Notifier_RequestTFA_FullMethodName                    = "/notifications.v1.Notifier/RequestTFA"
)

// NotifierClient is the client API for Notifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Handles time sensetive notifications with gRPC,
// less important ones are handled with MQs
type NotifierClient interface {
	// requests that a notification is sent to the user, the id, denote what service is requesting
	// the method is sms,email, push, etc
	// data is any additional data that needs to be included
	RequestNotification(ctx context.Context, in *NotificationRequest, opts ...grpc.CallOption) (*NotificationResponse, error)
	// removes the notification DB (the user deactivates acount or something)
	// the only required fields are service_id & username
	DeleteUser(ctx context.Context, in *NotificationRequest, opts ...grpc.CallOption) (*NotificationResponse, error)
	// updates the user's information, either email or phone must be filled
	RequestUserNotificationUpdate(ctx context.Context, in *UserNotificationUpdate, opts ...grpc.CallOption) (*UserNotificationResponse, error)
	// TODO change this to be a different protofile,
	// this is service-specific logic leaking
	// VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
	// requests a TFA notification (code will need to be generated)
	// Will i need to send code to the other service?
	RequestTFA(ctx context.Context, in *TFARequest, opts ...grpc.CallOption) (*TFAResponse, error)
}

type notifierClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifierClient(cc grpc.ClientConnInterface) NotifierClient {
	return &notifierClient{cc}
}

func (c *notifierClient) RequestNotification(ctx context.Context, in *NotificationRequest, opts ...grpc.CallOption) (*NotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificationResponse)
	err := c.cc.Invoke(ctx, Notifier_RequestNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifierClient) DeleteUser(ctx context.Context, in *NotificationRequest, opts ...grpc.CallOption) (*NotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificationResponse)
	err := c.cc.Invoke(ctx, Notifier_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifierClient) RequestUserNotificationUpdate(ctx context.Context, in *UserNotificationUpdate, opts ...grpc.CallOption) (*UserNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserNotificationResponse)
	err := c.cc.Invoke(ctx, Notifier_RequestUserNotificationUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifierClient) RequestTFA(ctx context.Context, in *TFARequest, opts ...grpc.CallOption) (*TFAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TFAResponse)
	err := c.cc.Invoke(ctx, Notifier_RequestTFA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifierServer is the server API for Notifier service.
// All implementations must embed UnimplementedNotifierServer
// for forward compatibility.
//
// Handles time sensetive notifications with gRPC,
// less important ones are handled with MQs
type NotifierServer interface {
	// requests that a notification is sent to the user, the id, denote what service is requesting
	// the method is sms,email, push, etc
	// data is any additional data that needs to be included
	RequestNotification(context.Context, *NotificationRequest) (*NotificationResponse, error)
	// removes the notification DB (the user deactivates acount or something)
	// the only required fields are service_id & username
	DeleteUser(context.Context, *NotificationRequest) (*NotificationResponse, error)
	// updates the user's information, either email or phone must be filled
	RequestUserNotificationUpdate(context.Context, *UserNotificationUpdate) (*UserNotificationResponse, error)
	// TODO change this to be a different protofile,
	// this is service-specific logic leaking
	// VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
	// requests a TFA notification (code will need to be generated)
	// Will i need to send code to the other service?
	RequestTFA(context.Context, *TFARequest) (*TFAResponse, error)
	mustEmbedUnimplementedNotifierServer()
}

// UnimplementedNotifierServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotifierServer struct{}

func (UnimplementedNotifierServer) RequestNotification(context.Context, *NotificationRequest) (*NotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestNotification not implemented")
}
func (UnimplementedNotifierServer) DeleteUser(context.Context, *NotificationRequest) (*NotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedNotifierServer) RequestUserNotificationUpdate(context.Context, *UserNotificationUpdate) (*UserNotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestUserNotificationUpdate not implemented")
}
func (UnimplementedNotifierServer) RequestTFA(context.Context, *TFARequest) (*TFAResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestTFA not implemented")
}
func (UnimplementedNotifierServer) mustEmbedUnimplementedNotifierServer() {}
func (UnimplementedNotifierServer) testEmbeddedByValue()                  {}

// UnsafeNotifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifierServer will
// result in compilation errors.
type UnsafeNotifierServer interface {
	mustEmbedUnimplementedNotifierServer()
}

func RegisterNotifierServer(s grpc.ServiceRegistrar, srv NotifierServer) {
	// If the following call panics, it indicates UnimplementedNotifierServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Notifier_ServiceDesc, srv)
}

func _Notifier_RequestNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifierServer).RequestNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Notifier_RequestNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifierServer).RequestNotification(ctx, req.(*NotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notifier_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifierServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Notifier_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifierServer).DeleteUser(ctx, req.(*NotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notifier_RequestUserNotificationUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserNotificationUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifierServer).RequestUserNotificationUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Notifier_RequestUserNotificationUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifierServer).RequestUserNotificationUpdate(ctx, req.(*UserNotificationUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notifier_RequestTFA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TFARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifierServer).RequestTFA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Notifier_RequestTFA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifierServer).RequestTFA(ctx, req.(*TFARequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Notifier_ServiceDesc is the grpc.ServiceDesc for Notifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Notifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notifications.v1.Notifier",
	HandlerType: (*NotifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestNotification",
			Handler:    _Notifier_RequestNotification_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Notifier_DeleteUser_Handler,
		},
		{
			MethodName: "RequestUserNotificationUpdate",
			Handler:    _Notifier_RequestUserNotificationUpdate_Handler,
		},
		{
			MethodName: "RequestTFA",
			Handler:    _Notifier_RequestTFA_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notifications/v1/notifications.proto",
}
